version: '3.9'

services:
  reverse-proxy:
    image: 127.0.0.1:5000/${BUILD_APP_PREFIX}-traefik
    restart: always
    ports:
      - '80:80'
      - '443:443'
    networks:
      - webgateway
    build:
      context: ./
      dockerfile: ./traefik.dockerfile
      network: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=webgateway"
        - "traefik.http.routers.reverse-proxy.rule=Host(`traefik.example.com`)"
        - "traefik.http.routers.reverse-proxy.service=api@internal"
        - "traefik.http.routers.reverse-proxy.entrypoints=http"
        - "traefik.http.services.reverse-proxy.loadbalancer.server.port=8080"
        - "traefik.http.routers.reverse-proxy.middlewares=api-auth"
        - "traefik.http.middlewares.api-auth.basicauth.usersFile=/etc/traefik/dashboard_basic_auth.env"
networks:
  webgateway:
    name: webgateway
    driver: overlay
