node_version: 18

local_paths:
  all_keys: "{{ playbook_dir | dirname }}/keys"
  envs: "{{ playbook_dir | dirname }}/envs"
  services: "{{ playbook_dir | dirname }}/services"

shared_paths:
  root: /var/www

all_groups:
  - name: webusers

all_users:
  - name: deploy
    groups: wheel,webusers,docker

  - name: web
    groups: webusers
