- name: Add Node GPG apt Key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add node Repository
  apt_repository:
    repo: "deb [arch=amd64] https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main"
    state: present

- name: Update apt and install nodejs
  apt:
    pkg: nodejs
    state: latest
    update_cache: true

- name: Install yarn
  npm:
    name: yarn
    state: present
    global: true

- name: Install zx
  npm:
    name: zx
    state: present
    global: true
