- name: Sync staging key / envs folders
  include_tasks: "{{ playbook_dir }}/roles/utils/tasks/copy-env-keys.yml"
  vars:
    src_paths:
      envs: "{{ staging_paths.local.envs }}"
      all_keys: "{{ staging_paths.local.all_keys }}"

    dest_paths:
      envs: "{{ staging_paths.envs }}"
      all_keys: "{{ staging_paths.all_keys }}"

- name: Sync staging scripts folder
  synchronize:
    src: "{{ staging_paths.local.service }}/scripts/"
    dest: "{{ staging_paths.root }}/scripts"
    rsync_opts:
      - "--chmod=F740"
      - "--chown=deploy:webusers"

- name: Sync docker folder
  synchronize:
    src: "{{ staging_paths.local.service }}/docker/"
    dest: "{{ staging_paths.root }}"
    rsync_opts:
      - "--chmod=F640"
      - "--chown=deploy:webusers"
