- name: Create root skeleton directories if not exists
  file:
    path: "{{ item }}"
    state: directory
    owner: deploy
    group: webusers
    mode: 0770
  loop:
    - "{{ shared_paths.root }}"
